[package]
name = "alloy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true }
engine = { workspace = true }
rhai-runtime = { workspace = true }
graphics = { workspace = true }
html = { workspace = true }
css = { workspace = true }
dom = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
rhai = { workspace = true }
