//! [`EngineFunction`] — the auxiliary trait PRD-002:49-51 names in the bound of
//! `register_fn` but never defines.
//!
//! It adapts an ordinary Rust closure into something an engine can call: it
//! takes a slice of [`EngineValue`] arguments and returns one [`EngineValue`],
//! mapping every conversion failure to [`EngineError`]. Blanket impls cover
//! closures of arity 0 through 7 (generated by `impl_engine_function!`) whose
//! parameters are [`FromEngineValue`] and whose result is [`IntoEngineValue`].
//! Fallible or variadic native functions register through
//! [`ExecutionContext::register_native_fn`][crate::ExecutionContext::register_native_fn]
//! directly; broader arity support can be added without changing this contract.

use crate::application::conversion::{FromEngineValue, IntoEngineValue};
use crate::domain::error::EngineError;
use crate::domain::value::EngineValue;

/// The number of arguments a native function accepts.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Arity(usize);

impl Arity {
    #[must_use]
    pub const fn exact(count: usize) -> Self {
        Self(count)
    }

    #[must_use]
    pub const fn count(self) -> usize {
        self.0
    }
}

/// A Rust callable exposed to scripts under a name. `Args` and `Ret` are marker
/// type parameters that let the blanket impls below stay non-overlapping.
pub trait EngineFunction<Args, Ret>: Send + Sync + 'static {
    /// Invoke with already-marshalled arguments.
    fn invoke(&self, arguments: &[EngineValue]) -> Result<EngineValue, EngineError>;

    /// How many arguments [`invoke`](Self::invoke) expects.
    fn arity(&self) -> Arity;
}

fn check_arity(arguments: &[EngineValue], expected: usize) -> Result<(), EngineError> {
    if arguments.len() == expected {
        return Ok(());
    }
    Err(EngineError::binding(format!(
        "expected {expected} argument(s), received {}",
        arguments.len()
    )))
}

fn argument<T: FromEngineValue>(arguments: &[EngineValue], index: usize) -> Result<T, EngineError> {
    let slot = arguments
        .get(index)
        .ok_or_else(|| EngineError::binding(format!("missing argument {index}")))?;
    T::from_engine_value(slot.clone())
}

/// Blanket [`EngineFunction`] impls for closures of arity 0 through 7 (the ceiling
/// `clippy::too_many_arguments` allows) whose parameters are [`FromEngineValue`]
/// and whose result is [`IntoEngineValue`]. `Args` is the parameter tuple; it
/// keeps the impls non-overlapping.
macro_rules! impl_engine_function {
    ( $arity:literal ; $( $ty:ident : $index:tt ),* ) => {
        impl<Function, $( $ty, )* Ret> EngineFunction<( $( $ty, )* ), Ret> for Function
        where
            Function: Fn( $( $ty ),* ) -> Ret + Send + Sync + 'static,
            $( $ty: FromEngineValue + 'static, )*
            Ret: IntoEngineValue + 'static,
        {
            fn invoke(&self, arguments: &[EngineValue]) -> Result<EngineValue, EngineError> {
                check_arity(arguments, $arity)?;
                Ok((self)( $( argument::<$ty>(arguments, $index)? ),* ).into_engine_value())
            }

            fn arity(&self) -> Arity {
                Arity::exact($arity)
            }
        }
    };
}

impl_engine_function!(0; );
impl_engine_function!(1; A0: 0);
impl_engine_function!(2; A0: 0, A1: 1);
impl_engine_function!(3; A0: 0, A1: 1, A2: 2);
impl_engine_function!(4; A0: 0, A1: 1, A2: 2, A3: 3);
impl_engine_function!(5; A0: 0, A1: 1, A2: 2, A3: 3, A4: 4);
impl_engine_function!(6; A0: 0, A1: 1, A2: 2, A3: 3, A4: 4, A5: 5);
impl_engine_function!(7; A0: 0, A1: 1, A2: 2, A3: 3, A4: 4, A5: 5, A6: 6);
