[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bitflags = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
dom = { workspace = true }
